apiVersion: apps/v1
kind: Deployment
metadata:
  name: firewolf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firewolf
  template:
    metadata:
      labels:
        app: firewolf
    spec:
      imagePullSecrets:
          - name: regcred
      containers:
        - name: firewolf
          env:
            - name: TZ
              value: Asia/Tokyo
          image: ghcr.io/h-orito/firewolf:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "1024Mi"
          volumeMounts:
            - name: wolf-log-storage
              mountPath: /app/logs
            - name: firebase-adminsdk-storage
              mountPath: /app/firebase
          envFrom:
          - secretRef:
              name: firewolf-secret
            prefix: FIREWOLF_
          - secretRef:
              name: mysql-secret
            prefix: MYSQL_
          - secretRef:
              name: twitter-secret
            prefix: TWITTER_
          - secretRef:
              name: slack-secret
            prefix: SLACK_
      nodeSelector:
        nodeName: worker
      volumes:
        - name: wolf-log-storage
          hostPath:
            path: /var/log/wolf
        - name: firebase-adminsdk-storage
          hostPath:
            path: /app/firebase
---
apiVersion: v1
kind: Service
metadata:
  name: firewolf
spec:
  ports:
    - port: 8087
      protocol: TCP
      targetPort: 8087
  selector:
    app: firewolf
  type: NodePort
