apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-uploader
  template:
    metadata:
      labels:
        app: image-uploader
    spec:
      imagePullSecrets:
          - name: regcred
      containers:
        - name: image-uploader
          env:
            - name: TZ
              value: Asia/Tokyo
          image: ghcr.io/h-orito/image-uploader:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          volumeMounts:
            - name: wolf-log-storage
              mountPath: /app/logs
            - name: image-storage
              mountPath: /var/www/html
      nodeSelector:
        nodeName: worker
      volumes:
        - name: wolf-log-storage
          hostPath:
            path: /var/log/wolf
        - name: image-storage
          hostPath:
            path: /mnt/vol1/www/html
---
apiVersion: v1
kind: Service
metadata:
  name: image-uploader
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: image-uploader
  type: NodePort
