apiVersion: apps/v1
kind: Deployment
metadata:
  name: lastwolf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lastwolf
  template:
    metadata:
      labels:
        app: lastwolf
    spec:
      imagePullSecrets:
          - name: regcred
      containers:
        - name: lastwolf
          env:
            - name: TZ
              value: Asia/Tokyo
          image: ghcr.io/h-orito/lastwolf:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "1024Mi"
          volumeMounts:
            - name: wolf-log-storage
              mountPath: /app/logs
            - name: firebase-adminsdk-storage
              mountPath: /app/firebase
          envFrom:
          - secretRef:
              name: lastwolf-secret
            prefix: LASTWOLF_
          - secretRef:
              name: mysql-secret
            prefix: MYSQL_
          - secretRef:
              name: twitter-secret
            prefix: TWITTER_
          - secretRef:
              name: slack-secret
            prefix: SLACK_
      nodeSelector:
        nodeName: worker
      volumes:
        - name: wolf-log-storage
          hostPath:
            path: /var/log/wolf
        - name: firebase-adminsdk-storage
          hostPath:
            path: /app/firebase
---
apiVersion: v1
kind: Service
metadata:
  name: lastwolf
spec:
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    app: lastwolf
  type: NodePort
